version: '3.9'

services:
  dev:
    image: codercom/code-server:latest  # صورة VS Code جاهزة للتشغيل عبر المتصفح
    container_name: vscode_dev
    ports:
      - "8050:8080"   # يمكن الوصول لـ VS Code من المتصفح عبر localhost:8080
    volumes:
      - ./:/home/coder/project  # ربط مشروعك مع الحاوية
    environment:
      PASSWORD: "changeme"  # كلمة مرور لتسجيل الدخول إلى VS Code
    restart: unless-stopped
